#pragma once

#include <Arduino.h>
#include "FranzMetronomeClickSample.h"  // Generated by wav2sketch at 16 kHz

class Metronome {
public:
    Metronome();
    void init();
    void setTempo(uint16_t bpm);        // BPM: beats per minute
    uint16_t getTempo();        // BPM: beats per minute
 
    void turn(bool onOff);              // Enable or disable the metronome
    bool isOn(); 
    
    void update();                      // Call often from loop()

private:
    bool enabled;
    uint32_t periodMicros;             // Interval between beats in microseconds
    uint32_t lastBeatMicros;           // Time of last beat
    void playClick();
};



extern void println(const char* format, ...);
